spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/forohub
spring.datasource.username=postgres
spring.datasource.password=Cr3sp0s
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=123456
server.port=8081